# Generated by Django 5.2.4 on 2025-07-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=50, unique=True)),
                ('submitted_by', models.CharField(max_length=50)),
                ('submitted_date', models.DateField()),
                ('tread_diameter_new', models.CharField(max_length=100)),
                ('last_shop_issue_size', models.CharField(max_length=100)),
                ('condemning_dia', models.CharField(max_length=100)),
                ('wheel_gauge', models.CharField(max_length=100)),
                ('variation_same_axle', models.CharField(max_length=50)),
                ('variation_same_bogie', models.CharField(max_length=50)),
                ('variation_same_coach', models.CharField(max_length=50)),
                ('wheel_profile', models.CharField(max_length=100)),
                ('intermediate_wwp', models.CharField(max_length=100)),
                ('bearing_seat_diameter', models.CharField(max_length=100)),
                ('roller_bearing_outer_dia', models.CharField(max_length=100)),
                ('roller_bearing_bore_dia', models.CharField(max_length=100)),
                ('roller_bearing_width', models.CharField(max_length=100)),
                ('axle_box_housing_bore_dia', models.CharField(max_length=100)),
                ('wheel_disc_width', models.CharField(max_length=100)),
            ],
        ),
    ]
