# Generated by Django 5.2.4 on 2025-07-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=50, unique=True)),
                ('inspection_by', models.CharField(max_length=50)),
                ('inspection_date', models.DateField()),
                ('bogie_no', models.CharField(max_length=50)),
                ('maker_year_built', models.CharField(max_length=50)),
                ('incoming_div_and_date', models.CharField(max_length=50)),
                ('deficit_components', models.CharField(max_length=100)),
                ('date_of_ioh', models.DateField()),
                ('bogie_frame_condition', models.CharField(max_length=50)),
                ('bolster', models.CharField(max_length=50)),
                ('bolster_suspension_bracket', models.CharField(max_length=50)),
                ('lower_spring_seat', models.CharField(max_length=50)),
                ('axle_guide', models.CharField(max_length=50)),
                ('cylinder_body', models.CharField(max_length=50)),
                ('piston_trunnion', models.CharField(max_length=50)),
                ('adjusting_tube', models.CharField(max_length=50)),
                ('plunger_spring', models.CharField(max_length=50)),
            ],
        ),
    ]
